name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify build
        run: pnpm build

      - name: Create .env.test file
        run: |
          echo "MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }}" > .env.test
          echo "MAINNET_ETHERSCAN_API_KEY=${{ secrets.MAINNET_ETHERSCAN_API_KEY }}" >> .env.test
          echo "MAINNET_BLOCKSCOUT_API_KEY=${{ secrets.MAINNET_BLOCKSCOUT_API_KEY }}" >> .env.test

      - name: Run Tests
        run: pnpm test

      - name: Run Typecheck
        run: pnpm typecheck
